### PR TITLE
Add client side validation locale support

### PR DESCRIPTION
**Pull request by laytan**
This PR is probably not finished but im creating this for thoughts.

This PR loads the wanted validatorjs locale instead of hardcoding it to English.
It also 'fixes' the ``php artisan vendor:publish --tag=aire-public-assets`` command.

One downside is that these public assets have to be vendor published to make the translations work.

I would like to know what you think of it.

### CODE REVIEW

**Comment by inxilpro** [comment]
Hm. I don't really like the idea of dynamically requiring the language file based on the config. I think I would rather just include the language file during the server side render process, [somewhere around line 116 of the client validation element](https://github.com/glhd/aire/blob/master/src/Elements/ClientValidation.php#L116).  We'd need to support both inline and remote options, but I just think that would keep things simpler for most people.

What do you think?

**Comment by laytan** [comment]
Yeah my solution might not be the simplest and best way to do it.

Including it through the render is a good idea. You mean like you are doing now with file_get_contents, and then choosing the specific file to include online according to the app's locale? 

If inlining is set to false how would you see that option working out? 

For inlining your solution is great.

**Comment by inxilpro** [comment]
> If inlining is set to false how would you see that option working out?

I think we'd just add a second configuration option. Something like `validation_lang_path` and set it to `NULL` by default (because the `'en'` lang is packaged with the validator). Then we could add a note there about using `https://unpkg.com/browse/validatorjs@3.4.0/dist/lang/` or publishing the language themselves if they need it.

**Comment by laytan** [comment]
Alright sounds good,

Should i try to implement this in another pull request or would you like to tackle it on your own?

**Comment by inxilpro** [comment]
If you'd like to take a shot at it, that'd be great! Otherwise, I probably won't be able to get to it for a little while.

**Pull request closed without merging**
